let a = 10;
let b = 20;
let temp;
console.log("the value of before swappnig a is",a);
console.log("the value of before swapping b is",b);
temp = a;
a = b;
b = temp;
console.log("the value of after swappnig a is",a);
console.log("the value of after swapping b is",b);